source 'https://rubygems.org'

gem 'rails', github: 'rails/rails', branch: '3-2-stable'

gem 'capistrano', require: false
gem 'capistrano-ext', require: false
gem 'capistrano_colors', require: false
gem 'rvm-capistrano', '>= 1.2.0', require: false
gem 'mechanize', '<= 2.7.2'
gem 'test-unit', '~> 3.0'
gem 'foreman', require: false
gem 'puma', require: false
gem "sinatra", require: false
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'clockwork', require: false
gem 'rack-cors', :require => 'rack/cors'
gem 'redcarpet'
gem 'gmaps4rails', '~> 2.1'
gem 'geokit'
gem 'georuby', require: false
gem 'turbolinks', '~> 2.3'
gem 'jquery-turbolinks'
gem 'strong_parameters', '0.1.6'
gem 'cache_digests'
gem 'dalli'
gem 'rack-cache', require: 'rack/cache'
gem 'prawn', '0.12.0', require: false
gem 'jbuilder'
gem "yajl-ruby"
gem "dealertool", path: "./gems/dealertool"
gem "inventur", path: "./gems/inventur"
gem 'builder', require: false
gem 'rake'
gem 'mysql2', '< 0.4'
gem 'pry'
gem 'eu_central_bank', github: "RubyMoney/eu_central_bank", branch: :master
gem 'bootstrap-will_paginate'
gem 'default_value_for'
gem 'tilt'
gem 'haml-rails'
gem 'haml'
gem 'ejs'
gem 'eco'
gem 'sass'
gem 'premailer-rails'
gem 'nokogiri', require: false
gem "jquery-fileupload-rails"
gem "oj"

group :development do
  gem 'mailcatcher'
  gem 'quiet_assets'
end

group :test do
  gem 'timecop'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'capybara-screenshot'
  gem 'webmock', require: false
  gem 'vcr'
  gem 'launchy'
end

group :test, :development do
  gem "byebug"
  gem 'rack-contrib'
  gem 'rspec-rails'
  gem 'factory_girl'
  gem 'faker'
  gem 'jasminerice'
  gem 'jasmine-headless-webkit'
end

gem 'handlebars_assets'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'bootstrap-sass', '~> 3.1.1'

  gem "font-awesome-rails", "~> 3.1.1.1"

  gem 'coffee-rails'
  gem 'select2-rails'
  gem 'webshims-rails'
  gem 'jquery-rails', '2.1.4'
  gem 'compass-rails'

  gem 'uglifier'
  gem 'turbo-sprockets-rails3'
end

gem 'shopify_api'
gem 'newrelic_rpm'
gem 'meta_search', '1.1.3', require: false
gem 'globalize','~> 3.0.0'
gem 'dragonfly'
gem 'rmagick', require: false
gem 'image_optim', :github => 'xxx/image_optim'
gem 'image_optim_pack'
gem 'annotate', '2.4.0', require: false
gem 'workflow', '0.8.1', require: false
gem 'rubyzip', '~> 0.9.4', require: false
gem 'uuidtools', '2.1.5', require: false
gem 'ean', '0.2.0', require: false
gem 'devise', '~> 2.2.4'
gem 'devise-encryptable'
gem 'cancan'
gem 'acts_as_list', '0.4.0', require: false
gem "Ascii85" #, "~> 1.0.1"
gem 'acts_as_xlsx', require: false
gem "axlsx", "~> 1.2", require: false
gem 'paypal_nvp'
gem 'dynamic_form'
